### ISSUE TITLE
Semantic operators

### ISSUE THREAD

**Issue by tomconroy** [ReactKit/ReactKit#10]
I like the simplicity of this project but it is incomplete without support for combining operations like `zip`, `combineLatest`, which are pretty essential. The `any` function looks like it's `merge` (which could be used as the basis for these other combining functions), but in other libraries `any` is a [boolean](http://rxmarbles.com/#any) [operation](https://github.com/ankurp/Dollar.swift#any). The different definitions for `map` should be named semantically like `scan`, `flatMap`, etc.

Do you have plans to support more of the operations from Rx? I am not smart enough to do the work myself

**Comment by inamiy** [comment]
Hi, thank you for feedback.
Actually, I'm quite new to Rx and functional programming,
so I'm currently learning and trying to implement each of Rx operations step by step.
(If you find any other core methods that are essential, please let me know)

For semantics, I'll try to implement **as same name as possible.**
I personally don't like some of Rx's method naming (e.g. `scan()` should be `mapAccumulate()`), so I'm planning to add a better name first, and then add its alias name for Rx users.

Also, in current ReactKit 0.4.0, I'm using too many *Swift overloads & explict 1st param* to group similar methods, but this seems a bad idea (less declarative) in functional programming world, so I'm planning to rename existing methods as well (e.g. auto-flattening `map(f: T -> Signal<T>)` to `flatMap()`.

**Comment by inamiy** [comment]
I added many more operations in #26, so it's good time to close this issue.
Thanks for your first feedback!

**Comment by tomconroy** [comment]
Yay!
