### ISSUE TITLE
Support CocoaPods

### ISSUE THREAD

**Issue by LightD** [ReactKit/ReactKit#20]
Why aren't you supporting cocoapods? all major libraries are supporting cocoapods.. it would add up to the awesome library you have here!
It just requires `use_framework`, I don't see why not?

**Comment by inamiy** [comment]
I tagged 0.7.1 just now and pushed to CocoaPods.
You can try it by adding Podfile as follows:

```
platform :ios, '8.0'
use_frameworks!

pod 'ReactKit'
```
