### ISSUE TITLE
carthage update --use-submodules fails with an error

### ISSUE THREAD

**Issue by slabko** [ReactKit/ReactKit#21]
When I'm trying to call `carthage update --use-submodules` it returns error:

    *** Fetching ReactKit
    *** Fetching SwiftTask
    *** Checking out SwiftTask at "2.6.3"
    *** Checking out ReactKit at "0.7.1"
    fatal: Not a git repository (or any of the parent directories): .git

The Carfile is pretty simple:

    github "ReactKit/ReactKit"

**Comment by inamiy** [comment]
I guess your `Cartfile` is in a non-git working folder.
Make sure you `git init` first when you want to use `--use-submodules ` option.

**Comment by slabko** [comment]
Thanks! Thats why --use-submodules actually exist. Sorry for such a strange question :)

**Comment by inamiy** [comment]
No problem :smile:
