### ISSUE TITLE
Question: How to concatenate streams that terminate?

### ISSUE THREAD

**Issue by DarthMike** [ReactKit/ReactKit#41]
Hi!

Again thanks for you work on the lib :) I'm still learning Reactive Programming, and I wonder if you could assist me on how to do something I encounter all the time.

Let's say you have one stream, which does some asynchronous work, gives a successful value and fulfills.

And then somewhere else you want to continue doing something after this, with another stream.

If you connect both streams with flatMap, the second stream will terminate as well, which is not what I intended.

What do you recommend to use in this case?

Thanks!

**Comment by DarthMike** [comment]
I've come up with a solution that makes it work. But I'm not sure it's elegant or correct. Some part of the code:

```swift
let stream = api.search(barcode)
                |> map { $0.searchableName }
                |> concat(Stream.never()) // Between stream boundaries
                |> flatMap { name in
                    return bgg.searchGames(name, type: .Games, match: .Loose)
                } |> take(1)
```

So basically I insert a `never` stream between stream boundaries, to keep the next stream alive.

**Comment by inamiy** [comment]
Thanks for pointing out this issue.
Current `flatMap()` has a different implementation compared to other Rx frameworks, 
and I should say this is a bug. 
Your code will be a good workaround, and I will try fixing this issue soon.

**Comment by DarthMike** [comment]
Thanks @inamiy .
I've got another question regarding streams which are bound. What is the behaviour of error propagation?

```swift
let stream = api.search(barcode) 
                |> flatMap {
                    return anotherStream(...)  // This stream fails via reject()
                }

```

I have two streams concatenated via flatmap, and then the second is rejected, but stream failure or completion callback is not called. Any clues what I might be missing?

**Comment by inamiy** [comment]
@DarthMike
In your case, if `anotherStream(...)` gets rejected, `stream` will also get rejected.
You can register callbacks like`stream.failure(callback)` or `stream.then(callback)` to check its being called, but doesn't it work for you?

**Comment by DarthMike** [comment]
@inamiy I subscribe via:
stream.react {
...
}.failure {
... 
}
But don't receive callbacks for failure

**Comment by DarthMike** [comment]
@inamiy Let me elaborate: It may be a side effect of my workaround with Stream.never().
The actual stream composition is:
```swift
 let stream = api.search(barcode)
                |> map { $0.searchableName }
                |> concat(Stream.never())
                |> flatMap { name in
                    return anotherStream(...)
                }
```

I've tried pointing my code to the `FlattenStyle` branch, and refactoring it to look like:
```swift
 let stream = api.search(barcode)
                |> map { $0.searchableName }
                |> flatMap(.Concat) { name in
                    return anotherStream(...)
                }
```

Then works properly with react + failure.

**Comment by inamiy** [comment]
@DarthMike
Hm, actually, I don't think `concat(Stream.never())` in your first code will affect the error propagation to downstream, so it should work just similar to second code...

But anyway! 
Important part is your second code, and if that's working correctly,
I think we are now able to merge #44.

Thanks for checking this issue :blush:
