### ISSUE TITLE
buttonSignal Missing argument for parameter #1 in call

### ISSUE THREAD

**Issue by katopz** [ReactKit/ReactKit#9]
Here's working fine
```swift
self.buttonSignal = self.button.buttonSignal("OK")
```
But, When I try...
```swift
self.buttonSignal = self.button.buttonSignal()
```
I got...
```
ViewController.swift:87:58: Missing argument for parameter #1 in call
```
So the question is that possible to "not send" any arg?

Thanks

**Comment by inamiy** [comment]
Hi.
In your case, you can use `Signal<Void>` type instead.
Make sure to define `buttonSignal` as `var buttonSignal: Signal<Void>?`,
because this will also affect type-inference.

![signal-void](https://cloud.githubusercontent.com/assets/138476/5604578/3c7830b6-9408-11e4-80a4-a8874917cbac.png)
